### ISSUE TITLE
Cannot add numbers to Attribute as Number

### ISSUE THREAD

**Issue by kamilwlf** [jonaslins/fiwareOrionLibrary#2]
In file Attribute.java  this field: `private String value;`

is defined as String, but I need add it as Number

**Comment by jonaslins** [comment]
Attribute value can also be other types. For now string is a simple way to match. You can parse it as a Number eg.: `Number num = Integer.parseInt(myString);`

**Comment by kamilwlf** [comment]
I need to save value on Orion as Number
Json should look like this:

> {
> "count":5
> }

now I can send only as String:

> {
> "count":"5"
> }
